const PRODUCTS=[
{id:1,name:"Terra Beige",category:"Керамогранит",texture:"Камень",format:"60×120",price:3490,pop:98,badge:"Новинка",unitArea:.72,stock:120,img:"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=85",desc:"Тёплый спокойный керамогранит с натуральной каменной фактурой. Подходит для пола, стен и современных минималистичных интерьеров."},
{id:2,name:"Calacatta Soft",category:"Керамогранит",texture:"Мрамор",format:"60×120",price:4890,pop:95,badge:"",unitArea:.72,stock:80,img:"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=85",desc:"Светлый мрамор с мягкими прожилками для выразительных стен и санузлов."},
{id:3,name:"Graphite Stone",category:"Керамогранит",texture:"Камень",format:"80×80",price:3990,pop:94,badge:"Хит",unitArea:.64,stock:70,img:"https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=900&q=85",desc:"Графитовый камень с матовой поверхностью и глубоким оттенком."},
{id:4,name:"Sand Terrazzo",category:"Керамическая плитка",texture:"Терраццо",format:"60×60",price:2990,pop:91,badge:"",unitArea:.36,stock:150,img:"https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=85",desc:"Светлое терраццо с деликатной крошкой."},
{id:5,name:"Oak Line",category:"Керамогранит",texture:"Дерево",format:"20×120",price:3290,pop:88,badge:"",unitArea:.24,stock:90,img:"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=85",desc:"Фактура натурального дуба в практичном керамограните."},
{id:6,name:"Concrete Mist",category:"Керамическая плитка",texture:"Бетон",format:"60×60",price:2490,pop:87,badge:"",unitArea:.36,stock:130,img:"https://images.unsplash.com/photo-1600566753051-f0b89df2dd90?auto=format&fit=crop&w=900&q=85",desc:"Нейтральный бетонный оттенок для спокойных современных интерьеров."},
{id:7,name:"Marble Vein",category:"Керамогранит",texture:"Мрамор",format:"80×80",price:5290,pop:84,badge:"Premium",unitArea:.64,stock:50,img:"https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=85",desc:"Премиальный выразительный мрамор с контрастной прожилкой."},
{id:8,name:"Mono Sand",category:"Мозаика",texture:"Камень",format:"30×90",price:2190,pop:80,badge:"",unitArea:.27,stock:100,img:"https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=900&q=85",desc:"Мелкоформатная коллекция в песочной гамме."},
{id:9,name:"Travertine Warm",category:"Керамогранит",texture:"Камень",format:"60×120",price:4190,pop:79,badge:"",unitArea:.72,stock:85,img:"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=85",desc:"Тёплый травертин с естественным рисунком."}];
let cart=JSON.parse(localStorage.getItem("forma_cart")||"[]"),fav=JSON.parse(localStorage.getItem("forma_fav")||"[]");
const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat("ru-RU").format(Math.round(n))+" ₽";
function save(){localStorage.setItem("forma_cart",JSON.stringify(cart));localStorage.setItem("forma_fav",JSON.stringify(fav));updateCounts()}
function updateCounts(){$("#cartCount").textContent=cart.reduce((a,x)=>a+x.qty,0);$("#favCount").textContent=fav.length}
function toast(t){const e=$("#toast")||document.body.appendChild(Object.assign(document.createElement("div"),{id:"toast",className:"toast"}));e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)}
function render(){let q=$("#catalogSearch").value.toLowerCase().trim(),cat=$("#categoryFilter").value,tex=$("#textureFilter").value,fmt=$("#formatFilter").value,min=Number($("#minPrice").value)||0,max=Number($("#maxPrice").value)||Infinity,arr=PRODUCTS.filter(p=>(!q||[p.name,p.texture,p.category,p.format].join(" ").toLowerCase().includes(q))&&(!cat||p.category===cat)&&(!tex||p.texture===tex)&&(!fmt||p.format===fmt)&&p.price>=min&&p.price<=max),sort=$("#sort").value;if(sort==="priceAsc")arr.sort((a,b)=>a.price-b.price);if(sort==="priceDesc")arr.sort((a,b)=>b.price-a.price);if(sort==="name")arr.sort((a,b)=>a.name.localeCompare(b.name));if(sort==="popular")arr.sort((a,b)=>b.pop-a.pop);$("#resultCount").textContent="Найдено: "+arr.length;$("#empty").style.display=arr.length?"none":"block";$("#products").innerHTML=arr.map(p=>`<article class="product"><div class="product-image" onclick="openProduct(${p.id})" style="cursor:pointer">${p.badge?`<span class="badge">${p.badge}</span>`:""}<button class="heart" onclick="event.stopPropagation();toggleFav(${p.id})">${fav.includes(p.id)?"♥":"♡"}</button><img src="${p.img}" alt="${p.name}"></div><div class="product-info"><div class="product-name">${p.name}</div><div class="product-meta"><span>${p.texture}</span><span>${p.format}</span></div><div class="product-price">от ${money(p.price)} / м²</div><button class="btn add" onclick="addCart(${p.id})">Добавить в корзину</button></div></article>`).join("")}
function openProduct(id){const p=PRODUCTS.find(x=>x.id===id);$("#productModalBody").innerHTML=`<div class="product-modal-grid"><img src="${p.img}" alt="${p.name}"><div><small class="eyebrow">${p.category} · ${p.texture}</small><h2>${p.name}</h2><p>${p.desc}</p><div class="specs"><span>Формат <b>${p.format}</b></span><span>Цена <b>${money(p.price)} / м²</b></span><span>В упаковке <b>${p.unitArea} м²</b></span><span>Остаток <b>${p.stock} уп.</b></span></div><div class="calc"><b>Расчёт плитки</b><label>Площадь помещения, м²<input id="areaInput" type="number" min="0" step=".1" placeholder="Например, 24"></label><label>Запас на подрезку<select id="wasteInput"><option value="0.05">5%</option><option value="0.10" selected>10%</option><option value="0.15">15%</option></select></label><div id="calcResult" class="calc-result">Введите площадь</div></div><button class="btn" onclick="addCart(${p.id});closeProduct()">Добавить в корзину</button></div></div>`;$("#productModal").classList.add("open");$("#areaInput").oninput=calculate;$("#wasteInput").oninput=calculate}
function calculate(){const p=PRODUCTS.find(x=>x.id===Number($("#productModalBody").querySelector(".btn").getAttribute("onclick").match(/\d+/)[0])),area=Number($("#areaInput").value)||0,waste=Number($("#wasteInput").value)||.1;if(!area){$("#calcResult").textContent="Введите площадь";return}const need=area*(1+waste),packs=Math.ceil(need/p.unitArea),real=packs*p.unitArea;$("#calcResult").innerHTML=`Нужно заказать: <b>${packs} уп.</b> · ${real.toFixed(2)} м²<br>Ориентировочно: <b>${money(real*p.price)}</b>`}
function closeProduct(){$("#productModal").classList.remove("open")}
function addCart(id,qty=1){let x=cart.find(i=>i.id===id);x?x.qty+=qty:cart.push({id,qty});save();openCart();toast("Товар добавлен в корзину")}
function toggleFav(id){fav.includes(id)?fav=fav.filter(x=>x!==id):fav.push(id);save();render()}
function openCart(){$("#drawerTitle").textContent="Корзина";$("#drawer").classList.add("open");$("#backdrop").classList.add("open");renderCart()}
function renderCart(){let body=$("#drawerBody");if(!cart.length){body.innerHTML="<div class='empty' style='display:block'>Корзина пуста.<br><br><a class='btn' href='#catalog' onclick='closeDrawer()'>Перейти в каталог</a></div>";return}let total=0;body.innerHTML=cart.map(i=>{let p=PRODUCTS.find(x=>x.id===i.id),sum=p.price*i.qty;total+=sum;return `<div class="cart-item"><img src="${p.img}" alt="${p.name}"><div><b>${p.name}</b><div class="muted">${money(p.price)} / м²</div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><span>${i.qty}</span><button onclick="changeQty(${p.id},1)">+</button></div></div><strong>${money(sum)}</strong></div>`}).join("");body.innerHTML+=`<div class="checkout"><div class="checkout-total"><span>Товары</span><span>${money(total)}</span></div><label class="checkout-label">Способ получения<select id="delivery"><option>Самовывоз — бесплатно</option><option>Доставка по Москве — рассчитаем после заказа</option><option>Доставка по России — рассчитаем после заказа</option></select></label><form id="orderForm"><input name="name" required placeholder="Имя"><input name="phone" required placeholder="Телефон"><input name="email" type="email" placeholder="Email"><input name="city" required placeholder="Город"><input name="address" placeholder="Адрес доставки"><textarea name="comment" placeholder="Комментарий к заказу"></textarea><label class="consent"><input type="checkbox" required> Согласен(а) с обработкой персональных данных</label><button class="btn">Перейти к оформлению заказа</button><small id="orderStatus"></small></form></div>`;$("#orderForm").onsubmit=submitOrder}
function submitOrder(e){e.preventDefault();const f=new FormData(e.target),order={number:"FORMA-"+Date.now().toString().slice(-8),items:cart.map(i=>({id:i.id,qty:i.qty})),customer:Object.fromEntries(f.entries()),delivery:$("#delivery").value,total:cart.reduce((s,i)=>s+PRODUCTS.find(p=>p.id===i.id).price*i.qty,0),createdAt:new Date().toISOString()};localStorage.setItem("forma_last_order",JSON.stringify(order));$("#orderStatus").textContent="Заказ сформирован. Для реальной онлайн-оплаты подключим ЮKassa на сервере.";cart=[];save();renderCart();toast("Заказ "+order.number+" создан")}
function changeQty(id,d){let x=cart.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(i=>i.id!==id);save();renderCart()}
function closeDrawer(){$("#drawer").classList.remove("open");$("#backdrop").classList.remove("open")}
function reset(){["#catalogSearch","#minPrice","#maxPrice"].forEach(s=>$(s).value="");["#categoryFilter","#textureFilter","#formatFilter"].forEach(s=>$(s).value="");render()}
$("#cartBtn").onclick=openCart;$("#drawerClose").onclick=closeDrawer;$("#backdrop").onclick=closeDrawer;$("#productModal").onclick=e=>{if(e.target.id==="productModal")closeProduct()};$("#searchBtn").onclick=()=>{$("#searchPanel").classList.toggle("open");$("#searchInput").focus()};$("#closeSearch").onclick=()=>$("#searchPanel").classList.remove("open");$("#searchInput").oninput=e=>{$("#catalogSearch").value=e.target.value;$("#catalog").scrollIntoView();render()};["#catalogSearch","#categoryFilter","#textureFilter","#formatFilter","#minPrice","#maxPrice","#sort"].forEach(s=>$(s).addEventListener("input",render));$("#resetFilters").onclick=reset;$("#favBtn").onclick=()=>{if(!fav.length){toast("Избранное пока пусто");return}toast("В избранном "+fav.length+" товар(а)")};$("#menuBtn").onclick=()=>$("#nav").classList.toggle("open");$("#consultForm").onsubmit=e=>{e.preventDefault();$("#formStatus").textContent="Спасибо! Заявка отправлена. Мы свяжемся с вами.";e.target.reset()};updateCounts();render();